[tool.poetry]
name = "arrow-odbc"
version = "0.1.0"
description = "Read the data of an ODBC data source as sequence of Apache Arrow record batches."
authors = ["Markus Klein"]

[tool.poetry.dependencies]
python = "^3.10"
arrow = "^1.2.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
